### ISSUE TITLE
具体如何部署能详细的步骤截图下吗？

### ISSUE THREAD

**Issue by Lemondogdog** [viyiviyi/ChatGLM-6B_Api_kaggle#1]
具体如何部署能详细的步骤截图下吗？

**Comment by viyiviyi** [comment]
可以的，我抽空整一下，整好了再回复你。

**Comment by viyiviyi** [comment]
> 具体如何部署能详细的步骤截图下吗？

可以的，我凑空整好了再回复你。

**Comment by viyiviyi** [comment]
写好了，希望有用。 https://github.com/viyiviyi/ChatGLM-6B_Api_kaggle/blob/main/%E9%83%A8%E7%BD%B2%E6%B5%81%E7%A8%8B%E5%9B%BE%E6%96%87.md
